### ISSUE TITLE
Background inpaiting training script

### ISSUE THREAD

**Issue by PierfrancescoArdino** [kathrinawu/CVPR2020-FutureVideoSynthesis#7]
Hi, could you share the training script for the background inpainting? It would be very useful to have both the training and the testing scripts. Thanks in advance

**Comment by kathrinawu** [comment]
Hi, the training of background inpainting is done by random crop in the background region of frames. The background region is computed using semantic maps. Other procedures are similar to the original code. This part of code is not cleaned up. If you still need them for reference, I can send you by email.

**Comment by PierfrancescoArdino** [comment]
> Hi, the training of background inpainting is done by random crop in the background region of frames. The background region is computed using semantic maps. Other procedures are similar to the original code. This part of code is not cleaned up. If you still need them for reference, I can send you by email.

Yes please. It would be very useful

**Comment by PierfrancescoArdino** [comment]
could you also send me the part for the video inpainting even if it is not cleaned up?

**Comment by kathrinawu** [comment]
please check your email box
